version: "1"
rules:
  - base: master
    upstream: i-nex:master
    mergeMethod: rebase
    mergeUnstable: false
    reviewers:
      - RogueScholar
    conflictReviewers:
      - RogueScholar
label: ":arrow_heading_down: pull"
