#!/bin/sh
#
# SPDX-FileCopyrightText: © 2009-2010 OpenELEC.tv <https://www.openelec.tv/>
# SPDX-FileCopyrightText: © 2020 Peter J. Mello <admin@petermello.net>
#
# SPDX-License-Identifier: GPL-2.0-or-later
# ------------------------------------------------------------------------------

TEMP=""

if lspci -n | grep 0300 | grep -q 10de; then
  [ -f /usr/bin/nvidia-smi ] &&
  TEMP="$(nvidia-smi --format=nounits,csv,noheader --query-gpu=temperature.gpu)"
fi

if lspci -n | grep 0300 | grep -q 1002; then
  [ -f /usr/bin/aticonfig ] &&
  TEMP="$(aticonfig --od-gettemperature | grep Temperature | awk '{print $5}' |
    cut -c1-2)"
fi

if [ -n "${TEMP}" ]; then
  echo "${TEMP} ℃"
fi
