' Gambas module file
'
' SPDX-FileCopyrightText: © 2013-2016 Michał Głowienka <eloaders@linux.pl>
' SPDX-FileCopyrightText: © 2020 Peter J. Mello <admin@petermello.net>
'
' SPDX-License-Identifier: GPL-3.0-or-later
' ------------------------------------------------------------------------------

Public Logs As New Logger
Public Sub _inits()
  Dim Do_not_print As String
  If Access(User.Home & "/", gb.Write) = False Then
  Message.Error("Cannot write files to " & User.Home & "/.config/i-nex")
  Endif

  If Exist(User.Home & "/.config/i-nex") Then
  Logs("I-Nex directory already exists in $HOME/.config folder", Logger.Info)
  Else
  Logs("I-Nex directory not found in $HOME/.config folder", Logger.Error)
  Create_Needed_Folders()
  Logs("I-Nex directory created in $HOME/.config folder", Logger.Info)
  Endif

  Do_not_print = Null
End

Private Function Create_Needed_Folders()
  Try Mkdir User.Home & "/.config/i-nex/"
End
